import { Test, TestingModule } from '@nestjs/testing';
import { HttpModule } from '@nestjs/axios';

import type { GetBoxscoreByGameIdRes } from '@nba-app/types-nba';

import { BoxscoreController } from './boxscore.controller';
import { BoxscoreService } from './boxscore.service';

describe('BoxscoreController', () => {
  let games: TestingModule;

  beforeAll(async () => {
    games = await Test.createTestingModule({
      imports: [HttpModule],
      controllers: [BoxscoreController],
      providers: [BoxscoreService],
    }).compile();
  });

  describe('getData', () => {
    it('should return list of games"', async () => {
      const result: GetBoxscoreByGameIdRes = {
        meta: {
          version: 1,
          code: 200,
          request: 'http://nba.cloud/games/0022000181/boxscore?Format=json',
          time: '2021-01-16 00:01:02.646846',
        },
        game: {
          gameId: '0022000181',
          gameTimeLocal: '2021-01-15T19:30:00-05:00',
          gameTimeUTC: '2021-01-16T00:30:00Z',
          gameTimeHome: '2021-01-15T19:30:00-05:00',
          gameTimeAway: '2021-01-15T19:30:00-05:00',
          gameEt: '2021-01-15T19:30:00-05:00',
          duration: 134,
          gameCode: '20210115/NYKCLE',
          gameStatusText: 'Final',
          gameStatus: 3,
          regulationPeriods: 4,
          period: 4,
          gameClock: 'PT00M00.00S',
          attendance: 1944,
          sellout: '0',
          arena: {
            arenaId: 1000006,
            arenaName: 'Rocket Mortgage FieldHouse',
            arenaCity: 'Cleveland',
            arenaState: 'OH',
            arenaCountry: 'US',
            arenaTimezone: 'America/New_York',
          },
          officials: [
            {
              personId: 1174,
              name: 'Ken Mauer',
              nameI: 'K. Mauer',
              firstName: 'Ken',
              familyName: 'Mauer',
              jerseyNum: '41',
              assignment: 'OFFICIAL1',
            },
            {
              personId: 200833,
              name: 'Eric Dalen',
              nameI: 'E. Dalen',
              firstName: 'Eric',
              familyName: 'Dalen',
              jerseyNum: '37',
              assignment: 'OFFICIAL2',
            },
            {
              personId: 1627963,
              name: 'Phenizee Ransom',
              nameI: 'P. Ransom',
              firstName: 'Phenizee',
              familyName: 'Ransom',
              jerseyNum: '70',
              assignment: 'OFFICIAL3',
            },
          ],
          homeTeam: {
            teamId: 1610612739,
            teamName: 'Cavaliers',
            teamCity: 'Cleveland',
            teamTricode: 'CLE',
            score: 106,
            inBonus: '1',
            timeoutsRemaining: 2,
            periods: [],
            players: [],
            statistics: {
              assists: 26,
              assistsTurnoverRatio: 1.625,
              benchPoints: 8,
              biggestLead: 12,
              biggestLeadScore: '68-80',
              biggestScoringRun: 16,
              biggestScoringRunScore: '84-80',
              blocks: 6,
              blocksReceived: 10,
              fastBreakPointsAttempted: 8,
              fastBreakPointsMade: 7,
              fastBreakPointsPercentage: 0.875,
              fieldGoalsAttempted: 79,
              fieldGoalsEffectiveAdjusted: 0.512658227848101,
              fieldGoalsMade: 36,
              fieldGoalsPercentage: 0.455696202531646,
              foulsOffensive: 2,
              foulsDrawn: 21,
              foulsPersonal: 18,
              foulsTeam: 16,
              foulsTechnical: 0,
              foulsTeamTechnical: 0,
              freeThrowsAttempted: 34,
              freeThrowsMade: 25,
              freeThrowsPercentage: 0.735294117647059,
              leadChanges: 8,
              minutes: 'PT240M00.00S',
              minutesCalculated: 'PT240M',
              points: 106,
              pointsAgainst: 103,
              pointsFastBreak: 20,
              pointsFromTurnovers: 19,
              pointsInThePaint: 54,
              pointsInThePaintAttempted: 50,
              pointsInThePaintMade: 27,
              pointsInThePaintPercentage: 0.54,
              pointsSecondChance: 18,
              reboundsDefensive: 34,
              reboundsOffensive: 14,
              reboundsPersonal: 48,
              reboundsTeam: 5,
              reboundsTeamDefensive: 0,
              reboundsTeamOffensive: 5,
              reboundsTotal: 53,
              secondChancePointsAttempted: 13,
              secondChancePointsMade: 6,
              secondChancePointsPercentage: 0.461538461538462,
              steals: 9,
              threePointersAttempted: 27,
              threePointersMade: 9,
              threePointersPercentage: 0.333333333333333,
              timeLeading: 'PT33M19.07S',
              timesTied: 6,
              trueShootingAttempts: 93.96,
              trueShootingPercentage: 0.56406981694338,
              turnovers: 15,
              turnoversTeam: 1,
              turnoversTotal: 16,
              twoPointersAttempted: 52,
              twoPointersMade: 27,
              twoPointersPercentage: 0.5192307692307689,
            },
          },
          awayTeam: {
            teamId: 1610612752,
            teamName: 'Knicks',
            teamCity: 'New York',
            teamTricode: 'NYK',
            score: 103,
            inBonus: '1',
            timeoutsRemaining: 0,
            periods: [
              {
                period: 1,
                periodType: 'REGULAR',
                score: 25,
              },
              {
                period: 2,
                periodType: 'REGULAR',
                score: 30,
              },
              {
                period: 3,
                periodType: 'REGULAR',
                score: 25,
              },
              {
                period: 4,
                periodType: 'REGULAR',
                score: 23,
              },
            ],
            players: [
              {
                status: 'ACTIVE',
                order: 1,
                personId: 203493,
                jerseyNum: '25',
                position: 'SF',
                starter: '1',
                oncourt: '1',
                played: '1',
                statistics: {
                  assists: 2,
                  blocks: 0,
                  blocksReceived: 1,
                  fieldGoalsAttempted: 5,
                  fieldGoalsMade: 2,
                  fieldGoalsPercentage: 0.4,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 2,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 76,
                  minutes: 'PT30M52.00S',
                  minutesCalculated: 'PT31M',
                  plus: 67,
                  plusMinusPoints: -9,
                  points: 4,
                  pointsFastBreak: 2,
                  pointsInThePaint: 4,
                  pointsSecondChance: 0,
                  reboundsDefensive: 1,
                  reboundsOffensive: 0,
                  reboundsTotal: 1,
                  steals: 2,
                  threePointersAttempted: 2,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 1,
                  twoPointersAttempted: 3,
                  twoPointersMade: 2,
                  twoPointersPercentage: 0.666666666666666,
                },
                name: 'Reggie Bullock',
                nameI: 'R. Bullock',
                firstName: 'Reggie',
                familyName: 'Bullock',
              },
              {
                status: 'ACTIVE',
                order: 2,
                personId: 203944,
                jerseyNum: '30',
                position: 'PF',
                starter: '1',
                oncourt: '1',
                played: '1',
                statistics: {
                  assists: 6,
                  blocks: 0,
                  blocksReceived: 2,
                  fieldGoalsAttempted: 20,
                  fieldGoalsMade: 11,
                  fieldGoalsPercentage: 0.55,
                  foulsOffensive: 0,
                  foulsDrawn: 5,
                  foulsPersonal: 3,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 5,
                  freeThrowsMade: 4,
                  freeThrowsPercentage: 0.8,
                  minus: 86,
                  minutes: 'PT38M03.00S',
                  minutesCalculated: 'PT38M',
                  plus: 85,
                  plusMinusPoints: -1,
                  points: 28,
                  pointsFastBreak: 2,
                  pointsInThePaint: 10,
                  pointsSecondChance: 2,
                  reboundsDefensive: 5,
                  reboundsOffensive: 1,
                  reboundsTotal: 6,
                  steals: 0,
                  threePointersAttempted: 4,
                  threePointersMade: 2,
                  threePointersPercentage: 0.5,
                  turnovers: 1,
                  twoPointersAttempted: 16,
                  twoPointersMade: 9,
                  twoPointersPercentage: 0.5625,
                },
                name: 'Julius Randle',
                nameI: 'J. Randle',
                firstName: 'Julius',
                familyName: 'Randle',
              },
              {
                status: 'ACTIVE',
                order: 3,
                personId: 1629011,
                jerseyNum: '23',
                position: 'C',
                starter: '1',
                oncourt: '1',
                played: '1',
                statistics: {
                  assists: 0,
                  blocks: 1,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 5,
                  fieldGoalsMade: 2,
                  fieldGoalsPercentage: 0.4,
                  foulsOffensive: 0,
                  foulsDrawn: 2,
                  foulsPersonal: 4,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 2,
                  freeThrowsMade: 1,
                  freeThrowsPercentage: 0.5,
                  minus: 74,
                  minutes: 'PT28M01.00S',
                  minutesCalculated: 'PT28M',
                  plus: 55,
                  plusMinusPoints: -19,
                  points: 5,
                  pointsFastBreak: 0,
                  pointsInThePaint: 4,
                  pointsSecondChance: 0,
                  reboundsDefensive: 4,
                  reboundsOffensive: 2,
                  reboundsTotal: 6,
                  steals: 3,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 5,
                  twoPointersMade: 2,
                  twoPointersPercentage: 0.4,
                },
                name: 'Mitchell Robinson',
                nameI: 'M. Robinson',
                firstName: 'Mitchell',
                familyName: 'Robinson',
              },
              {
                status: 'ACTIVE',
                order: 4,
                personId: 1629628,
                jerseyNum: '9',
                position: 'SG',
                starter: '1',
                oncourt: '1',
                played: '1',
                statistics: {
                  assists: 3,
                  blocks: 2,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 12,
                  fieldGoalsMade: 7,
                  fieldGoalsPercentage: 0.583333333333333,
                  foulsOffensive: 0,
                  foulsDrawn: 6,
                  foulsPersonal: 2,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 4,
                  freeThrowsMade: 4,
                  freeThrowsPercentage: 1,
                  minus: 73,
                  minutes: 'PT32M58.00S',
                  minutesCalculated: 'PT33M',
                  plus: 73,
                  plusMinusPoints: 0,
                  points: 20,
                  pointsFastBreak: 2,
                  pointsInThePaint: 8,
                  pointsSecondChance: 0,
                  reboundsDefensive: 4,
                  reboundsOffensive: 0,
                  reboundsTotal: 4,
                  steals: 0,
                  threePointersAttempted: 4,
                  threePointersMade: 2,
                  threePointersPercentage: 0.5,
                  turnovers: 4,
                  twoPointersAttempted: 8,
                  twoPointersMade: 5,
                  twoPointersPercentage: 0.625,
                },
                name: 'RJ Barrett',
                nameI: 'R. Barrett',
                firstName: 'RJ',
                familyName: 'Barrett',
              },
              {
                status: 'ACTIVE',
                order: 5,
                personId: 203901,
                jerseyNum: '6',
                position: 'PG',
                starter: '1',
                oncourt: '0',
                played: '1',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 7,
                  fieldGoalsMade: 4,
                  fieldGoalsPercentage: 0.5714285714285711,
                  foulsOffensive: 0,
                  foulsDrawn: 1,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 1,
                  freeThrowsMade: 1,
                  freeThrowsPercentage: 1,
                  minus: 52,
                  minutes: 'PT20M27.00S',
                  minutesCalculated: 'PT20M',
                  plus: 38,
                  plusMinusPoints: -14,
                  points: 9,
                  pointsFastBreak: 0,
                  pointsInThePaint: 8,
                  pointsSecondChance: 0,
                  reboundsDefensive: 2,
                  reboundsOffensive: 1,
                  reboundsTotal: 3,
                  steals: 0,
                  threePointersAttempted: 1,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 3,
                  twoPointersAttempted: 6,
                  twoPointersMade: 4,
                  twoPointersPercentage: 0.666666666666666,
                },
                name: 'Elfrid Payton',
                nameI: 'E. Payton',
                firstName: 'Elfrid',
                familyName: 'Payton',
              },
              {
                status: 'ACTIVE',
                order: 6,
                personId: 203085,
                jerseyNum: '8',
                starter: '0',
                oncourt: '0',
                played: '1',
                statistics: {
                  assists: 2,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 6,
                  fieldGoalsMade: 1,
                  fieldGoalsPercentage: 0.166666666666667,
                  foulsOffensive: 0,
                  foulsDrawn: 1,
                  foulsPersonal: 2,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 30,
                  minutes: 'PT17M08.00S',
                  minutesCalculated: 'PT17M',
                  plus: 36,
                  plusMinusPoints: 6,
                  points: 2,
                  pointsFastBreak: 0,
                  pointsInThePaint: 2,
                  pointsSecondChance: 0,
                  reboundsDefensive: 2,
                  reboundsOffensive: 0,
                  reboundsTotal: 2,
                  steals: 0,
                  threePointersAttempted: 4,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 1,
                  twoPointersAttempted: 2,
                  twoPointersMade: 1,
                  twoPointersPercentage: 0.5,
                },
                name: 'Austin Rivers',
                nameI: 'A. Rivers',
                firstName: 'Austin',
                familyName: 'Rivers',
              },
              {
                status: 'ACTIVE',
                order: 7,
                personId: 203457,
                jerseyNum: '3',
                starter: '0',
                oncourt: '0',
                played: '1',
                statistics: {
                  assists: 0,
                  blocks: 6,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 3,
                  fieldGoalsMade: 2,
                  fieldGoalsPercentage: 0.666666666666666,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 4,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 26,
                  minutes: 'PT17M28.00S',
                  minutesCalculated: 'PT17M',
                  plus: 41,
                  plusMinusPoints: 15,
                  points: 4,
                  pointsFastBreak: 0,
                  pointsInThePaint: 4,
                  pointsSecondChance: 2,
                  reboundsDefensive: 3,
                  reboundsOffensive: 1,
                  reboundsTotal: 4,
                  steals: 1,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 1,
                  twoPointersAttempted: 3,
                  twoPointersMade: 2,
                  twoPointersPercentage: 0.666666666666666,
                },
                name: 'Nerlens Noel',
                nameI: 'N. Noel',
                firstName: 'Nerlens',
                familyName: 'Noel',
              },
              {
                status: 'ACTIVE',
                order: 8,
                personId: 1630193,
                jerseyNum: '5',
                starter: '0',
                oncourt: '1',
                played: '1',
                statistics: {
                  assists: 4,
                  blocks: 1,
                  blocksReceived: 3,
                  fieldGoalsAttempted: 17,
                  fieldGoalsMade: 9,
                  fieldGoalsPercentage: 0.529411764705882,
                  foulsOffensive: 0,
                  foulsDrawn: 2,
                  foulsPersonal: 3,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 2,
                  freeThrowsMade: 2,
                  freeThrowsPercentage: 1,
                  minus: 54,
                  minutes: 'PT27M33.00S',
                  minutesCalculated: 'PT28M',
                  plus: 65,
                  plusMinusPoints: 11,
                  points: 23,
                  pointsFastBreak: 5,
                  pointsInThePaint: 12,
                  pointsSecondChance: 3,
                  reboundsDefensive: 4,
                  reboundsOffensive: 1,
                  reboundsTotal: 5,
                  steals: 1,
                  threePointersAttempted: 7,
                  threePointersMade: 3,
                  threePointersPercentage: 0.428571428571429,
                  turnovers: 0,
                  twoPointersAttempted: 10,
                  twoPointersMade: 6,
                  twoPointersPercentage: 0.6,
                },
                name: 'Immanuel Quickley',
                nameI: 'I. Quickley',
                firstName: 'Immanuel',
                familyName: 'Quickley',
              },
              {
                status: 'ACTIVE',
                order: 9,
                personId: 1628995,
                jerseyNum: '20',
                starter: '0',
                oncourt: '0',
                played: '1',
                statistics: {
                  assists: 1,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 5,
                  fieldGoalsMade: 2,
                  fieldGoalsPercentage: 0.4,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 39,
                  minutes: 'PT17M33.00S',
                  minutesCalculated: 'PT18M',
                  plus: 37,
                  plusMinusPoints: -2,
                  points: 6,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 4,
                  reboundsOffensive: 0,
                  reboundsTotal: 4,
                  steals: 1,
                  threePointersAttempted: 2,
                  threePointersMade: 2,
                  threePointersPercentage: 1,
                  turnovers: 0,
                  twoPointersAttempted: 3,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Kevin Knox II',
                nameI: 'K. Knox II',
                firstName: 'Kevin',
                familyName: 'Knox II',
              },
              {
                status: 'ACTIVE',
                order: 10,
                personId: 1630167,
                jerseyNum: '1',
                starter: '0',
                oncourt: '0',
                played: '1',
                statistics: {
                  assists: 2,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 2,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 1,
                  foulsPersonal: 1,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 2,
                  freeThrowsMade: 2,
                  freeThrowsPercentage: 1,
                  minus: 20,
                  minutes: 'PT09M57.00S',
                  minutesCalculated: 'PT10M',
                  plus: 18,
                  plusMinusPoints: -2,
                  points: 2,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 3,
                  reboundsOffensive: 1,
                  reboundsTotal: 4,
                  steals: 1,
                  threePointersAttempted: 1,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 1,
                  twoPointersAttempted: 1,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Obi Toppin',
                nameI: 'O. Toppin',
                firstName: 'Obi',
                familyName: 'Toppin',
              },
              {
                status: 'ACTIVE',
                order: 11,
                personId: 1629649,
                jerseyNum: '17',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Ignas Brazdeikis',
                nameI: 'I. Brazdeikis',
                firstName: 'Ignas',
                familyName: 'Brazdeikis',
              },
              {
                status: 'ACTIVE',
                order: 12,
                personId: 201959,
                jerseyNum: '67',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Taj Gibson',
                nameI: 'T. Gibson',
                firstName: 'Taj',
                familyName: 'Gibson',
              },
              {
                status: 'ACTIVE',
                order: 13,
                personId: 1629607,
                jerseyNum: '0',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Jared Harper',
                nameI: 'J. Harper',
                firstName: 'Jared',
                familyName: 'Harper',
              },
              {
                status: 'ACTIVE',
                order: 14,
                personId: 1629033,
                jerseyNum: '21',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Theo Pinson',
                nameI: 'T. Pinson',
                firstName: 'Theo',
                familyName: 'Pinson',
              },
              {
                status: 'ACTIVE',
                order: 15,
                personId: 1628372,
                jerseyNum: '4',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Dennis Smith Jr.',
                nameI: 'D. Smith Jr.',
                firstName: 'Dennis',
                familyName: 'Smith Jr.',
              },
              {
                status: 'INACTIVE',
                notPlayingReason: 'INACTIVE_INJURY',
                notPlayingDescription: 'Left Ankle; sprained',
                order: 16,
                personId: 202692,
                jerseyNum: '18',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Alec Burks',
                nameI: 'A. Burks',
                firstName: 'Alec',
                familyName: 'Burks',
              },
              {
                status: 'INACTIVE',
                notPlayingReason: 'INACTIVE_INJURY',
                notPlayingDescription: 'Right Knee; sprained',
                order: 17,
                personId: 1628373,
                jerseyNum: '11',
                starter: '0',
                oncourt: '0',
                played: '0',
                statistics: {
                  assists: 0,
                  blocks: 0,
                  blocksReceived: 0,
                  fieldGoalsAttempted: 0,
                  fieldGoalsMade: 0,
                  fieldGoalsPercentage: 0,
                  foulsOffensive: 0,
                  foulsDrawn: 0,
                  foulsPersonal: 0,
                  foulsTechnical: 0,
                  freeThrowsAttempted: 0,
                  freeThrowsMade: 0,
                  freeThrowsPercentage: 0,
                  minus: 0,
                  minutes: 'PT00M00.00S',
                  minutesCalculated: 'PT00M',
                  plus: 0,
                  plusMinusPoints: 0,
                  points: 0,
                  pointsFastBreak: 0,
                  pointsInThePaint: 0,
                  pointsSecondChance: 0,
                  reboundsDefensive: 0,
                  reboundsOffensive: 0,
                  reboundsTotal: 0,
                  steals: 0,
                  threePointersAttempted: 0,
                  threePointersMade: 0,
                  threePointersPercentage: 0,
                  turnovers: 0,
                  twoPointersAttempted: 0,
                  twoPointersMade: 0,
                  twoPointersPercentage: 0,
                },
                name: 'Frank Ntilikina',
                nameI: 'F. Ntilikina',
                firstName: 'Frank',
                familyName: 'Ntilikina',
              },
            ],
            statistics: {
              assists: 20,
              assistsTurnoverRatio: 1.53846153846154,
              benchPoints: 37,
              biggestLead: 6,
              biggestLeadScore: '39-33',
              biggestScoringRun: 16,
              biggestScoringRunScore: '84-80',
              blocks: 10,
              blocksReceived: 6,
              fastBreakPointsAttempted: 6,
              fastBreakPointsMade: 4,
              fastBreakPointsPercentage: 0.666666666666666,
              fieldGoalsAttempted: 82,
              fieldGoalsEffectiveAdjusted: 0.542682926829268,
              fieldGoalsMade: 40,
              fieldGoalsPercentage: 0.48780487804878,
              foulsOffensive: 0,
              foulsDrawn: 18,
              foulsPersonal: 21,
              foulsTeam: 21,
              foulsTechnical: 0,
              foulsTeamTechnical: 0,
              freeThrowsAttempted: 16,
              freeThrowsMade: 14,
              freeThrowsPercentage: 0.875,
              leadChanges: 8,
              minutes: 'PT240M00.00S',
              minutesCalculated: 'PT240M',
              points: 103,
              pointsAgainst: 106,
              pointsFastBreak: 11,
              pointsFromTurnovers: 23,
              pointsInThePaint: 52,
              pointsInThePaintAttempted: 41,
              pointsInThePaintMade: 26,
              pointsInThePaintPercentage: 0.634146341463415,
              pointsSecondChance: 7,
              reboundsDefensive: 32,
              reboundsOffensive: 7,
              reboundsPersonal: 39,
              reboundsTeam: 4,
              reboundsTeamDefensive: 1,
              reboundsTeamOffensive: 3,
              reboundsTotal: 43,
              secondChancePointsAttempted: 8,
              secondChancePointsMade: 3,
              secondChancePointsPercentage: 0.375,
              steals: 9,
              threePointersAttempted: 25,
              threePointersMade: 9,
              threePointersPercentage: 0.36,
              timeLeading: 'PT09M49.00S',
              timesTied: 6,
              trueShootingAttempts: 89.04,
              trueShootingPercentage: 0.578391734052111,
              turnovers: 12,
              turnoversTeam: 1,
              turnoversTotal: 13,
              twoPointersAttempted: 57,
              twoPointersMade: 31,
              twoPointersPercentage: 0.5438596491228069,
            },
          },
        },
      };

      jest
        .spyOn(
          games.get<BoxscoreService>(BoxscoreService),
          'getBoxscoreByGameId'
        )
        .mockImplementation(async () => result);

      expect(
        await games
          .get<BoxscoreController>(BoxscoreController)
          .getBoxscoreByGameId({ gameId: '12345' })
      ).toEqual(result);
    });
  });
});
